### ISSUE TITLE
Edit German language page

### ISSUE THREAD

**Issue by simabasel** [simabasel/psycorona.org#11]
@JoKra1 could you please check the following comments that I received from a team member: 

I received the following comments from one of the team members: 

Some things I noticed:
-German version has no home button. 
-If I click the virus icon in the top left, it brings me back to the English main page. 
-The line break looks weird on German main page, since only the "19" is on the next line. 
-Also, the "about" text is google translated I assume? Lacking some basic grammar at points.

Thanks!

**Comment by JoKra1** [comment]
@simabasel
 
All changes currently in **develop** brand:
- added missing Home button to German Navbar
- fixed virus icon
- I tried a few things but the <h> tag ignores my line-breaks, changed "Auswirkungen" to "Effekte"
to achieve a better layout, meaning is the same
- Sorry about the poor translation I did not give it a lot of thought, basically translated just word by word. Will add a thoughtful translation later this evening.

Once I fix the translation I will request another pull. If you want to make changes in the next 2 hours, could you make them to the develop branch? Then we can make sure that the next merge will include all changes. :-)

JK

**Comment by simabasel** [comment]
Awesome, thanks. Take your time to work on this. Also note that I removed
the virus Icon since we added the "Home" button.

Let's keep it simple and clean looking. Thanks again!

On Tue, Mar 31, 2020 at 9:53 PM Joshua Krause <notifications@github.com>
wrote:

> @simabasel
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=ANo1ShUNxFuyO7DtfCcbZ7O6lJ3QKiYLubibbld700k&s=QJB0CF0Wem0Jo9oZHFTduvGcegcWBK2VQLMitUrflL0&e=>
>
> All changes currently in *develop* brand:
>
>    - added missing Home button to German Navbar
>    - fixed virus icon
>    - I tried a few things but the tag ignores my line-breaks, changed
>    "Auswirkungen" to "Effekte"
>    to achieve a better layout, meaning is the same
>    - Sorry about the poor translation I did not give it a lot of thought,
>    basically translated just word by word. Will add a thoughtful translation
>    later this evening.
>
> Once I fix the translation I will request another pull. If you want to
> make changes in the next 2 hours, could you make them to the develop
> branch? Then we can make sure that the next merge will include all changes.
> :-)
>
> JK
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_issues_11-23issuecomment-2D606778723&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=ANo1ShUNxFuyO7DtfCcbZ7O6lJ3QKiYLubibbld700k&s=Geoq7uOe6NG6_5Gf8fI-TfsI9eqBhRAJaEUc-HudLDM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOBXPDXE4QQEGMEC7AQAGG3RKIUWBANCNFSM4LXYBMAQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=ANo1ShUNxFuyO7DtfCcbZ7O6lJ3QKiYLubibbld700k&s=tsEqsq3WmOP8mmBa3jYPVuGh7DQY51WmYGVOI8GZGOw&e=>
> .
>


-- 
*Sima Basel*
*Research Associate *
Social Science Experimental Laboratory
New York University Abu Dhabi

Office Tel (UAE): +971 2 628 5676
Mobile (UAE): +971 52 399 8961

www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>
