### ISSUE TITLE
List of team members 

### ISSUE THREAD

**Issue by simabasel** [simabasel/psycorona.org#12]
List of collaborators:
[full list here](https://docs.google.com/spreadsheets/d/1_GTcPqT6yauTFJ5v4jaqHxGvNqpsVceHYJfQZkSSAKQ/edit?usp=sharing)

To be added to the table in the "team" section. The order goes as follows:
organizing team at the top, below is everyone else.

**Comment by simabasel** [comment]
Hi @JoKra1 could you please add everyone who said "yes" in the google sheet to the table of team members? Thank you!

**Comment by JoKra1** [comment]
I created the table for both the German and English content version but I was unsure about the order you requested in your first comment. Thus, I created separate files for the tables for now. Hope that helps!
