### ISSUE TITLE
Edit FAQ section

### ISSUE THREAD

**Issue by simabasel** [simabasel/psycorona.org#22]
Create two subjections for the Qs: 
General and Privacy & Security. 

Similar to this list: https://docs.google.com/spreadsheets/d/12RUdIXraDn2cgkZloHB4rFqhd97sTCOZJUttZB0sWN0/edit#gid=0

Edit each question where to get the answer you have to click on the question and that reveals the answer instead of just displaying all the text at once.

**Comment by JoKra1** [comment]
I added the hide/show click functionality. You might want to add the different sections before you merge the request since I forgot to add those. :)

**Comment by simabasel** [comment]
Great! Thank you.

On Mon, Apr 13, 2020 at 1:29 AM Joshua Krause <notifications@github.com>
wrote:

> I added the hide/show click functionality. You might want to add the
> different sections before you merge the request since I forgot to add
> those. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_issues_22-23issuecomment-2D612678524&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=hoBRfoVUTRatUOSTnuCbTH2YSB1frhVxOPbiHoXCgsc&s=6oP94TEhZGog1eS5nxiZeIcZvgVtOKPSEypBXg79v-o&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOBXPDRLVDVT3B3S5KW7BPDRMIXCTANCNFSM4MFOUMIA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=hoBRfoVUTRatUOSTnuCbTH2YSB1frhVxOPbiHoXCgsc&s=QLy7smpZC5aDZjsraWJKborZe56cSfBvy8rak1X5-7w&e=>
> .
>


-- 
*Sima Basel*
*Research Associate *
Social Science Experimental Laboratory
New York University Abu Dhabi

Office Tel (UAE): +971 2 628 5676
Mobile (UAE): +971 52 399 8961

www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>
