### ISSUE TITLE
Add new pages

### ISSUE THREAD

**Issue by simabasel** [simabasel/psycorona.org#6]
Add the following pages: 

- _About this study_ page with general info (study aims)
- _FAQ_ page with more extensive info on privacy

**Comment by JoKra1** [comment]
I saw you uploaded a "more information" page already. Does that one cover the about this study page or do you think an additional one is needed?

**Comment by simabasel** [comment]
Good point, I can rename it to "about this study". Thanks for all your help
so far!

On Sat, Mar 28, 2020 at 9:17 PM Joshua Krause <notifications@github.com>
wrote:

> I saw you uploaded a "more information" page already. Does that one cover
> the about this study page or do you think an additional one is needed?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_simabasel_psycorona.org_issues_6-23issuecomment-2D605491189&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=JYQtQjomTuYevN6HD_F6cR79_2nniLX0-B1zuCVPQIQ&s=vHgSPJvg-BFmh0hHsEwe4OT_Uo985tCTO3kTlLUXaLM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOBXPDVTNHWWIHBT7Z5ZLQLRJYWLRANCNFSM4LVBFGSA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OH8A0VqMVR3GJIWIEtfU4A&m=JYQtQjomTuYevN6HD_F6cR79_2nniLX0-B1zuCVPQIQ&s=X0wDzQDvzU1aWiwd8B0fPrgMb7nE7QkHx1VRwy9tHjE&e=>
> .
>


-- 
*Sima Basel*
*Research Associate *
Social Science Experimental Laboratory
New York University Abu Dhabi

Office Tel (UAE): +971 2 628 5676
Mobile (UAE): +971 52 399 8961

www.nyuad.nyu.edu <http://www.nyu.edu/global-ties>
